"""Crear tablas iniciales

Revision ID: 89a02b04bde5
Revises: 
Create Date: 2026-03-03 21:30:29.472706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a02b04bde5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)

    op.create_table('sesiones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tense', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('puntaje_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('texto_generado_ia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('sesiones_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sesiones_pkey'))
    )
    op.create_index(op.f('ix_sesiones_id'), 'sesiones', ['id'], unique=False)

    op.create_table('progreso_habilidades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('puntaje', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('progreso_habilidades_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('progreso_habilidades_pkey'))
    )
    op.create_index(op.f('ix_progreso_habilidades_id'), 'progreso_habilidades', ['id'], unique=False)

    op.create_table('detalle_respuestas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sesion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verbo_infinitivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('respuesta_correcta', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('respuesta_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('puntaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('categoria_error', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('feedback_ia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], name=op.f('detalle_respuestas_sesion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('detalle_respuestas_pkey'))
    )
    op.create_index(op.f('ix_detalle_respuestas_id'), 'detalle_respuestas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_respuestas_id'), table_name='detalle_respuestas')
    op.drop_table('detalle_respuestas')
    op.drop_index(op.f('ix_progreso_habilidades_id'), table_name='progreso_habilidades')
    op.drop_table('progreso_habilidades')
    op.drop_index(op.f('ix_sesiones_id'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###